### PR TITLE
Add an `--beta` script CLI option 🌈

### PR DESCRIPTION
**Pull request by yvan-sraka**
This basically add `--features beta` to cargo options

### CODE REVIEW

**Comment by AureliaDolo** [comment]
That does the job on the python side, but for now the beta stuff does not exist on massa side right ?

**Comment by yvan-sraka** [comment]
> That does the job on the python side, but for now the beta stuff does not exist on massa side right ?

You're right, we need to edit the `Cargo.toml` to add the feature :)

**Review by AureliaDolo — APPROVED** [review]

**Review by damip — APPROVED** [review]
LGTM

**Comment by AureliaDolo** [comment]
bors merge

**Comment by damip** [comment]
bors merge

**Pull request merged**
